### ISSUE TITLE
dependencies https://github.com/adamyi/v6dns/issues/3#issuecomment-253207594

### ISSUE THREAD

**Issue by Opensourcecommunitydevelopment** [GJSmith3rd/dns-over-http2#1]
enabled issues and updated Version6mod

it requires following packages To Run:
npm install defaultable dev-null dnsd ip6 randomstring request url spdy

**Comment by Opensourcecommunitydevelopment** [comment]
Okay i now see: 

```

module.js:457
    throw err;
    ^

Error: Cannot find module 'defaultable'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\app\dns-over-http2\dnsd\server.js:5:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```
